language: node_js
script: npm run test-ci
node_js:
- node
- '4'
- '0.12'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
  - eng+build+privatestate@wealthfront.com
deploy:
  provider: npm
  email: ops+npm@wealthfront.com
  api_key:
    secure: flKaVtPSWZqTTvPNWkCepbCvinLK+1hzsBEPplOh/QvgP3eFOvRGqToD0ltMRCe/aoZROrZuyC2dq6+utB3xdgHzvi04LZAhWPnvyw2yDFYVR1rdWHFPkdPXY7SHIlxJ6Qe/ys13+8UpsEOoISbEuOikaMf2bqmpjyVm1kQ+mEDgfDKdIjCre9svsWwwxIWKn69WWspZ9NCyptbIoywdveC5N5s1EZ8nGv26tP7dBNuQdiYhtAon5QsBqESCnDekUkGfVzuRVVLv9Dc6k9xEdL2v/xlMQCpnmwS1CN6t3JDh5wX8gY8yz21+qp6HQVux9hVhbvIKdJ1+i43f6CGXLsLSo+LQkPcz+ppRb6IwAGIK8ylWoqgygl37rxpUijriwnUp0DZ3TyV7uGnA8WId8hiMC5ebPLTVoJiWrfNl1+nGhS933EgDqLB0qavDQMzSpzXzRsu7SjwUy2ddullvdmKrA4wgafATjPB5v+blAJYx34e1+hlRnl3ZX6f04MCjbTWbHrdrShr9v8XOg/5dbTMrvTHj7/ZGFiW2vDeGI+j0vqLJgMouvjzq8lmmhoZFZxZydd1U04hnHx8RhNT2vBuuKPTzZh4yL+KqikahHjZxRWgpOsY6jkEx/i8FpnY615Craoy1LIsBFVLB6As8x0cYr0QLYhBPx91Ll7ZJxPk=
  on:
    tags: true
    repo: wealthfront/private-state
    node: node
