language: node_js
script: npm run test-ci
node_js:
- node
- '4'
- '0.12'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
  - eng+build+privatestate@wealthfront.com
deploy:
  provider: npm
  email: ops+npm@wealthfront.com
  api_key:
    secure: uzqhBKQkTNDOxyjiV6K+7LouBDNgPIAU9cOM9sty5iW5KUQdEJxM5hGHxhaRIn6rjjcs1bMe9IzPxW9whYJokz4RdAx94LAzGJ9KK64iDHUsf/FeBSyUOkxARAodMjKo14WpLSdeq2SRJZaRrEv/+xoK5v/BtNbRqjCpOq8fnKn0ATJBAUdVLLp1/5jxODN1pEmeq4bFj1vtFzj5pcgtDmgN6Bx9lPUfG9ghSgv0TjPMBtj2zgXIMJaCQnXH//AVfiaF2TGu3a4FPnS6A7rvx6iuVNdPidaMQFC1FxX0dvFphVjdkHUzNudro89tMEHuee9xVl3t1zvuFUf/NG47tRdYWbIgi8Uf8n7gV5etjnnsZstRerCQICMzdvqggNDixLDdDcz7xuH1KHY5CFniZ/0H00Te0YeG7lgbwDLmEajfdGfu00uRbc2l7mk62hNdc8NBb86JWPFsdtclWzcrQZ7dqT8UZ9nlfZvzBTjQA+07hd5nElyPlSOkrgt447Oe/lZnivJYFtZoE5TrJldwe0saXACfRakI4zK7CbRCbsVePpMW25xAQipjrtmn0dgnl09kOpAHCJwG3NwKdo52fuDyadrTtH200ssWhopApZqcEfze6Sa+3sVbVVg6ceKJXqGntFQVoKO2zP7JPR3qGCXw856ANySne9YpaAmU6FU=
  on:
    tags: true
    repo: wealthfront/privatestate
    node: node
